namespace: ipfs
resources:
#- ipfs-auth-middleware.yaml
- ipfs-ingress.yaml
- ipfs-service.yaml
- ipfs-statefulset.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ipfs-set-bootstrap-conf
  files:
  - custom/configure-ipfs.sh
- name: ipfs-site
  literals:
  # TODO: improve this
  - public-hostname=opcube.local
secretGenerator:
- name: basic-auth
  files:
  - usersFile=secrets/basic-auth
vars:
- name: IPFS_PUBLIC_HOST
  objref:
    kind: ConfigMap
    name: ipfs-site
    apiVersion: v1
  fieldref:
    fieldpath: data.public-hostname
